#!/usr/bin/env python3
"""Regenerate every sunmeow icon, favicon, tray state and banner from one vector master.

Master: ``branding/meow/sunmeow.svg`` (the only hand-authored artwork). Everything this
script writes is generated -- never hand-edit a PNG/ICO/ICNS/JPG or a generated SVG; change
the master (or the layout constants below) and re-run::

    bash scripts/icons/meow/build.sh

Most outputs deliberately REPLACE the content of upstream Sunshine files under their
existing names (``sunshine.svg``, ``sunshine.ico``, ``images/sunshine-playing.svg`` ...),
because upstream code, CMake and packaging reference those paths. Renaming them would be a
code edit in a dozen upstream files; replacing bytes is not. Each replaced file is declared
in ``docs/meow/TOUCHPOINTS.md`` under the ``green-brand`` family.

Tools: ``rsvg-convert`` (librsvg) for rasterising and Pillow for PNG/ICO/ICNS/JPEG packing.
This mirrors meowerse ``packages/brand/scripts/build.sh`` (dark ``#0d0d0d`` plate, green
``#00ff82`` mark, Pillow packing) but rasterises each size from the vector instead of
down-sampling one bitmap, so 16 px stays crisp.
"""

import io
import os
import re
import shutil
import struct
import subprocess
import sys
import xml.etree.ElementTree as ET

from PIL import Image

# Brand tokens -- meowerse packages/ui/src/styles/tokens.css, kept in sync by hand.
GREEN = "#00ff82"  # --mw-green
PLATE = "#0d0d0d"  # --surface-0 (dark)
SURFACE_1 = "#161616"  # --surface-1 (dark)
INK = "#f2f2f2"  # --text-primary (dark)
INK_2 = "#a8a8a2"  # --text-secondary (dark)
AMBER = "#f5a524"  # --warning (dark)

#: Tray badge colours. Sunshine used #00ff00 / #00d9ff / #999999; these keep the three
#: states distinguishable by colour AND shape while staying inside the meowerse palette.
BADGES = {
    "playing": GREEN,  # streaming: brand green, play triangle
    "pausing": AMBER,  # paused: warning amber, pause bars
    "locked": INK,  # pairing request: near-white, padlock
}
BADGE_CX, BADGE_CY, BADGE_R, BADGE_RING = 192, 192, 52, 14

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
MASTER = os.path.join(ROOT, "branding", "meow", "sunmeow.svg")
WEB = os.path.join(ROOT, "src_assets", "common", "assets", "web", "public", "images")
SVG_NS = "http://www.w3.org/2000/svg"


def load_master():
    """Return the id -> element map of the master SVG."""
    tree = ET.parse(MASTER)
    return {el.get("id"): el for el in tree.iter() if el.get("id")}


M = load_master()
PLATE_D = M["plate"].get("d")
GLYPH_T = M["glyph"].get("transform")
GLYPH_D = "".join(p.get("d") for p in M["glyph"].iter(f"{{{SVG_NS}}}path"))
WORDMARK_D = M["wordmark"].get("d")
WORDMARK_ADV = float(M["wordmark"].get("data-advance"))


#: In-place marker for the generated SVGs, which overwrite upstream files: keeps them visible
#: to ``git grep -n 'MEOW-TOUCH'`` like every other touch-point (docs/meow/TOUCHPOINTS.md).
MARKER = ("<!-- MEOW-TOUCH(green-brand): generated by scripts/icons/meow/build.sh from "
          "branding/meow/sunmeow.svg; do not edit -->")


def svg_doc(body, w=256, h=256, vw=None, vh=None):
    """Wrap ``body`` in a standalone SVG document carrying the touch-point marker."""
    vw, vh = vw or w, vh or h
    return (f'<svg xmlns="{SVG_NS}" width="{w}" height="{h}" viewBox="0 0 {vw} {vh}">'
            f"{MARKER}{body}</svg>\n")


def glyph(fill=GREEN, transform=GLYPH_T):
    """The sun, in the 256 grid, at its place on the plate."""
    return f'<path fill="{fill}" transform="{transform}" d="{GLYPH_D}"/>'


def plated():
    """Plate + sun: the application icon."""
    return f'<path fill="{PLATE}" d="{PLATE_D}"/>' + glyph()


def badged(state):
    """Application icon with a tray-state badge in the lower-right corner.

    The badge sits on a plate-coloured ring so it reads as cut out of the sun; the ring
    stays inside the plate's rounded corner (checked in ``selfcheck``).
    """
    return (plated()
            + f'<circle cx="{BADGE_CX}" cy="{BADGE_CY}" r="{BADGE_R + BADGE_RING}" fill="{PLATE}"/>'
            + f'<circle cx="{BADGE_CX}" cy="{BADGE_CY}" r="{BADGE_R}" fill="{BADGES[state]}"/>'
            + f'<path fill="{PLATE}" d="{M["badge-" + state].get("d")}"/>')


def banner(w, h, mark, text_h, gap, layout="row", tagline=False):
    """Dark banner: sun on the left (row) or above (column), wordmark in ink.

    ``mark`` is the plate edge in px, ``text_h`` the wordmark em size in px.
    """
    s = text_h / 100.0
    tw = WORDMARK_ADV * s
    if layout == "row":
        total = mark + gap + tw
        mx, my = (w - total) / 2, (h - mark) / 2
        tx, ty = mx + mark + gap, h / 2 + 0.35 * text_h
    else:
        total = mark + gap + 0.72 * text_h
        mx, my = (w - mark) / 2, (h - total) / 2
        tx, ty = (w - tw) / 2, my + mark + gap + 0.72 * text_h
    k = mark / 256.0
    body = (f'<rect width="{w}" height="{h}" fill="{PLATE}"/>'
            f'<g transform="translate({mx:.2f} {my:.2f}) scale({k:.5f})">{plated()}</g>'
            f'<path fill="{INK}" transform="translate({tx:.2f} {ty:.2f}) scale({s:.5f})" d="{WORDMARK_D}"/>')
    return svg_doc(body, w, h)


def render(svg, w, h=None):
    """Rasterise an SVG string at w x h with rsvg-convert."""
    h = h or w
    out = subprocess.run(["rsvg-convert", "-w", str(w), "-h", str(h), "-f", "png"],
                         input=svg.encode(), capture_output=True, check=True).stdout
    return Image.open(io.BytesIO(out)).convert("RGBA")


def write(path, data):
    """Write text or bytes, creating parent dirs; report the path relative to the repo."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if isinstance(data, str):
        data = data.encode("utf-8")  # LF + UTF-8 on every OS, so outputs match everywhere
    with open(path, "wb") as fh:
        fh.write(data)
    print("  " + os.path.relpath(path, ROOT))


def save_png(img, path):
    """Save an optimised PNG."""
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    write(path, buf.getvalue())


def _ico_entries(blob):
    """Split an .ico into [(16-byte ICONDIRENTRY without offset, image bytes)]."""
    count = struct.unpack_from("<HHH", blob)[2]
    out = []
    for i in range(count):
        entry = blob[6 + 16 * i: 6 + 16 * (i + 1)]
        size, offset = struct.unpack_from("<II", entry, 8)
        out.append((entry[:8], blob[offset:offset + size]))
    return out


def save_ico(svg, path, sizes=(16, 20, 24, 32, 40, 48, 64, 96, 128, 256), bmp_upto=0):
    """Multi-resolution .ico, every size rasterised from the vector (no down-sampling).

    Frames up to ``bmp_upto`` px are stored as 32-bit BMP, larger ones as PNG. The root
    ``sunshine.ico`` (Windows exe resource, WiX, CPack) uses ``bmp_upto=128`` to keep
    upstream's frame layout, since some resource/installer tooling only accepts BMP
    small frames; the web favicons were all-PNG upstream and stay so.
    """
    imgs = {s: render(svg, s) for s in sizes}
    parts = []
    for fmt, group in (("bmp", [s for s in sizes if s <= bmp_upto]),
                       ("png", [s for s in sizes if s > bmp_upto])):
        if not group:
            continue
        buf = io.BytesIO()
        imgs[group[-1]].save(buf, format="ICO", sizes=[(s, s) for s in group],
                             append_images=[imgs[s] for s in group[:-1]], bitmap_format=fmt)
        parts += _ico_entries(buf.getvalue())
    offset = 6 + 16 * len(parts)
    head, body = [struct.pack("<HHH", 0, 1, len(parts))], []
    for entry, data in parts:
        head.append(entry + struct.pack("<II", len(data), offset))
        body.append(data)
        offset += len(data)
    write(path, b"".join(head + body))


def save_icns(path):
    """macOS .icns on Apple's icon grid: the plate is 824/1024 of the canvas, centred.

    Pillow writes the ic07-ic14 types (32@2x .. 1024); it has no writer for the legacy
    1x ic04/ic05 (16/32 px), which macOS derives by scaling ic11/ic12 instead.
    """
    def mac(size):
        inner = size * 824 / 1024
        off = (size - inner) / 2
        k = inner / 256.0
        return render(svg_doc(f'<g transform="translate({off:.3f} {off:.3f}) scale({k:.6f})">{plated()}</g>',
                              size, size), size)
    imgs = {s: mac(s) for s in (32, 64, 128, 256, 512, 1024)}
    buf = io.BytesIO()
    imgs[1024].save(buf, format="ICNS", append_images=[imgs[s] for s in (32, 64, 128, 256, 512)])
    write(path, buf.getvalue())


def save_jpg(img, path):
    """Save an opaque, progressive JPEG."""
    buf = io.BytesIO()
    img.convert("RGB").save(buf, format="JPEG", quality=92, optimize=True, progressive=True)
    write(path, buf.getvalue())


def selfcheck():
    """Fail loudly if the layout constants would draw outside the plate or off the badge."""
    # plate corner radius from the master's first arc
    m = re.search(r"A([\d.]+) ", PLATE_D)
    r = float(m.group(1))
    corner = 256 - r
    ring = BADGE_R + BADGE_RING
    reach = ((BADGE_CX + ring * 0.7071 - corner) ** 2 + (BADGE_CY + ring * 0.7071 - corner) ** 2) ** 0.5
    if reach > r:
        sys.exit(f"badge ring leaves the plate corner ({reach:.1f} > {r})")
    # every badge glyph must sit inside its disc (the glyph paths are absolute coordinates)
    for state in BADGES:
        img = render(svg_doc(f'<path fill="#fff" d="{M["badge-" + state].get("d")}"/>'), 256)
        px = img.load()
        worst = max(((x + 0.5 - BADGE_CX) ** 2 + (y + 0.5 - BADGE_CY) ** 2) ** 0.5
                    for y in range(256) for x in range(256) if px[x, y][3] > 8)
        if worst > BADGE_R - 4:
            sys.exit(f"badge-{state} glyph reaches {worst:.1f} from the disc centre (r {BADGE_R})")


def main():
    if not shutil.which("rsvg-convert"):
        sys.exit("rsvg-convert (librsvg) not found")
    selfcheck()
    app_svg = svg_doc(plated())
    print("application icon:")
    # sunshine.svg: hicolor app icon (cmake/packaging/linux.cmake), default tray icon
    # (emitted as images/logo-sunshine.svg by vite.config.js's emitTrayIconsPlugin), README, docs.
    write(os.path.join(ROOT, "sunshine.svg"), app_svg)
    save_png(render(app_svg, 256), os.path.join(ROOT, "sunshine.png"))  # CPACK_PACKAGE_ICON
    save_ico(app_svg, os.path.join(ROOT, "sunshine.ico"), bmp_upto=128)  # exe resource, WiX, CPack
    save_icns(os.path.join(ROOT, "src_assets", "macos", "build", "sunshine.icns"))
    save_png(render(app_svg, 256), os.path.join(ROOT, "gh-pages-template", "assets", "img", "navbar-avatar.png"))

    print("web UI:")
    save_ico(app_svg, os.path.join(WEB, "sunshine.ico"))  # favicon (index.html)
    save_png(render(app_svg, 16), os.path.join(WEB, "logo-sunshine-16.png"))
    save_png(render(app_svg, 45), os.path.join(WEB, "logo-sunshine-45.png"))  # navbar logo

    print("tray states:")
    for state in BADGES:
        svg = svg_doc(badged(state))
        base = os.path.join(WEB, f"sunshine-{state}")
        write(base + ".svg", svg)  # what src/system_tray.cpp loads
        save_png(render(svg, 256), base + ".png")
        save_png(render(svg, 16), base + "-16.png")
        save_png(render(svg, 45), base + "-45.png")
        save_ico(svg, base + ".ico")

    print("store / marketing art:")
    # MS Store box art: square, full-bleed dark with the mark inside the safe area.
    box = svg_doc(f'<rect width="1080" height="1080" fill="{PLATE}"/>'
                  f'<g transform="translate(216 216) scale(2.53125)">{glyph()}</g>', 1080, 1080)
    save_png(render(box, 1080), os.path.join(ROOT, "branding", "ms-store", "box-art.png"))
    poster = banner(720, 1080, 360, 120, 70, layout="column")
    save_png(render(poster, 720, 1080).convert("RGB"),
             os.path.join(ROOT, "branding", "ms-store", "poster-art.png"))
    save_jpg(render(banner(1280, 640, 256, 150, 56), 1280, 640),
             os.path.join(ROOT, "branding", "github", "banner.jpg"))
    # macOS DMG window background: plain dark surface with a quiet wordmark bottom-right,
    # clear of where Finder places the app and Applications icons.
    s = 36 / 100.0
    dmg = svg_doc(f'<rect width="953" height="504" fill="{SURFACE_1}"/>'
                  f'<path fill="{INK_2}" transform="translate({953 - 32 - WORDMARK_ADV * s:.2f} {504 - 32:.2f}) scale({s})" '
                  f'd="{WORDMARK_D}"/>', 953, 504)
    save_jpg(render(dmg, 953, 504),
             os.path.join(ROOT, "src_assets", "macos", "build", "sunshine-background-72dpi.jpg"))


if __name__ == "__main__":
    main()
